<script lang="ts">
</script>

<svelte:head>
  <title>Terms of Use - ChillieChat</title>
</svelte:head>

<div class="min-h-[100dvh] bg-gray-900 text-gray-200 py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-3xl mx-auto bg-gray-800 rounded-xl shadow-2xl p-8 border border-gray-700">
    <h1 class="text-3xl font-bold text-white mb-2">Terms of Use for ChillieChat</h1>
    <p class="text-sm text-indigo-400 mb-8">Effective Date: April 6, 2026</p>

    <div class="space-y-8">
      <section>
        <h2 class="text-xl font-semibold text-white mb-3 flex items-center">
          <span class="bg-indigo-600 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm mr-3">1</span>
          Acceptance of Terms
        </h2>
        <p class="text-gray-300 leading-relaxed">
          By downloading, installing, or using the ChillieChat application, you agree to comply with and be bound by these Terms of Use. If you do not agree with any of these terms, you are prohibited from using the application.
        </p>
      </section>

      <section>
        <h2 class="text-xl font-semibold text-white mb-3 flex items-center">
          <span class="bg-indigo-600 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm mr-3">2</span>
          User-Generated Content (UGC) Guidelines
        </h2>
        <p class="text-gray-300 leading-relaxed mb-4">
          ChillieChat relies heavily on User-Generated Content and AI interaction. To ensure a safe and respectful environment for all users, you agree <strong>NOT</strong> to post, share, or transmit any content that:
        </p>
        <ul class="list-disc list-inside space-y-2 text-gray-300 ml-6">
          <li>Contains sexually explicit material, nudity, or pornography.</li>
          <li>Promotes, depicts, or incites violence, self-harm, or illegal acts.</li>
          <li>Includes excessively foul, abusive, or profane language.</li>
          <li>Constitutes hate speech, harassment, bullying, or discrimination based on race, religion, gender, sexual orientation, or disability.</li>
          <li>Violates the intellectual property rights or privacy of others.</li>
        </ul>
      </section>

      <section>
        <h2 class="text-xl font-semibold text-white mb-3 flex items-center">
          <span class="bg-indigo-600 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm mr-3">3</span>
          Reporting & Blocking
        </h2>
        <p class="text-gray-300 leading-relaxed">
          We maintain a zero-tolerance policy for objectionable content or abusive behavior. ChillieChat provides built-in tools for users to flag/report inappropriate content and block abusive users. We reserve the right to review reported content and ban or remove any user or content that violates these Terms of Use without prior notice.
        </p>
      </section>

      <section>
        <h2 class="text-xl font-semibold text-white mb-3 flex items-center">
          <span class="bg-indigo-600 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm mr-3">4</span>
          AI Interactions
        </h2>
        <p class="text-gray-300 leading-relaxed">
          The application facilitates conversations with AI agents. While we strive to moderate the AI outputs to adhere to safety guidelines, you acknowledge that AI-generated responses can sometimes be unpredictable. We are not liable for the content generated by the AI, though we provide reporting mechanisms to correct unintended behavior.
        </p>
      </section>

      <section>
        <h2 class="text-xl font-semibold text-white mb-3 flex items-center">
          <span class="bg-indigo-600 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm mr-3">5</span>
          Account Suspension & Termination
        </h2>
        <p class="text-gray-300 leading-relaxed">
          We reserve the right to suspend or terminate your access to ChillieChat at any time, for any reason, including but not limited to the violation of these Terms of Use. Severe violations involving illegal content or threats will be reported to the appropriate authorities.
        </p>
      </section>

      <section>
        <h2 class="text-xl font-semibold text-white mb-3 flex items-center">
          <span class="bg-indigo-600 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm mr-3">6</span>
          Contact Information
        </h2>
        <div class="bg-gray-900 p-4 rounded-lg border border-gray-700 text-gray-300">
          <p class="mb-1">If you have any questions about these Terms of Use, please contact:</p>
          <ul class="list-none space-y-2 mt-4 font-mono text-sm">
            <li><span class="text-indigo-400">Developer:</span> Timothy Pulley</li>
            <li><span class="text-indigo-400">Email:</span> chilliemanbusiness@gmail.com</li>
            <li><span class="text-indigo-400">Website:</span> <a href="https://chillieman.com" class="hover:text-indigo-300 transition-colors">https://chillieman.com</a></li>
          </ul>
        </div>
      </section>
    </div>
    
    <div class="mt-12 pt-6 border-t border-gray-700 text-center">
      <a href="/" class="text-indigo-400 hover:text-indigo-300 transition-colors inline-flex items-center">
        <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path></svg>
        Return to NexusFest
      </a>
    </div>
  </div>
</div>